import type { Comment } from './types';

const AVATAR_KARAFLAS = 'https://i.pravatar.cc/150?u=karaflas8';
const AVATAR_GOZERO = 'https://i.pravatar.cc/150?u=gozero1';
const AVATAR_STATHIS = 'https://i.pravatar.cc/150?u=stathisntonas';
const AVATAR_ALEX = 'https://i.pravatar.cc/150?u=alexk';

export const mockComments: Comment[] = [
  {
    id: 'root-1',
    authorId: 'user-1',
    editedAt: null,
    commentLiked: true,
    content: 'Test',
    createdAt: '2024-09-30T11:25:00.000Z',
    parentCommentId: null,
    authorProfile: {
      id: 'user-1',
      firstName: 'Karaflas Eight',
      isStaff: false,
      avatarUri: AVATAR_KARAFLAS,
    },
    totalCommentLikes: 2,
    childCommentCount: 2,
    childComments: [
      {
        id: 'child-1-1',
        authorId: 'user-2',
        editedAt: null,
        commentLiked: false,
        content: 'Test',
        createdAt: '2024-09-30T11:26:00.000Z',
        parentCommentId: 'root-1',
        authorProfile: {
          id: 'user-2',
          firstName: 'Go Zero',
          isStaff: false,
          avatarUri: AVATAR_GOZERO,
        },
        totalCommentLikes: 1,
        childCommentCount: 2,
        childComments: [
          {
            id: 'child-1-1-1',
            authorId: 'user-3',
            editedAt: null,
            commentLiked: false,
            content: 'Test',
            createdAt: '2024-09-30T11:27:00.000Z',
            parentCommentId: 'child-1-1',
            authorProfile: {
              id: 'user-3',
              firstName: 'Stathis',
              isStaff: true,
              avatarUri: AVATAR_STATHIS,
            },
            totalCommentLikes: 0,
            childCommentCount: 1,
            childComments: [
              {
                id: 'child-1-1-1-1',
                authorId: 'user-4',
                editedAt: null,
                commentLiked: false,
                content: 'Deep reply here!',
                createdAt: '2024-09-30T11:28:00.000Z',
                parentCommentId: 'child-1-1-1',
                authorProfile: {
                  id: 'user-4',
                  firstName: 'Alex K',
                  isStaff: false,
                  avatarUri: AVATAR_ALEX,
                },
                totalCommentLikes: 0,
                childCommentCount: 0,
                childComments: [],
              },
            ],
          },
          {
            id: 'child-1-1-2',
            authorId: 'user-1',
            editedAt: null,
            commentLiked: false,
            content: 'Another nested reply',
            createdAt: '2024-09-30T11:29:00.000Z',
            parentCommentId: 'child-1-1',
            authorProfile: {
              id: 'user-1',
              firstName: 'Karaflas Eight',
              isStaff: false,
              avatarUri: AVATAR_KARAFLAS,
            },
            totalCommentLikes: 0,
            childCommentCount: 0,
            childComments: [],
          },
        ],
      },
      {
        id: 'child-1-2',
        authorId: 'user-1',
        editedAt: null,
        commentLiked: false,
        content: 'Test',
        createdAt: '2024-09-30T11:30:00.000Z',
        parentCommentId: 'root-1',
        authorProfile: {
          id: 'user-1',
          firstName: 'Karaflas Eight',
          isStaff: false,
          avatarUri: AVATAR_KARAFLAS,
        },
        totalCommentLikes: 0,
        childCommentCount: 0,
        childComments: [],
      },
    ],
  },
  {
    id: 'root-2',
    authorId: 'user-3',
    editedAt: null,
    commentLiked: false,
    content: 'This is a great feature!',
    createdAt: '2024-09-30T10:00:00.000Z',
    parentCommentId: null,
    authorProfile: {
      id: 'user-3',
      firstName: 'Stathis',
      isStaff: true,
      avatarUri: AVATAR_STATHIS,
    },
    totalCommentLikes: 5,
    childCommentCount: 2,
    childComments: [
      {
        id: 'child-2-1',
        authorId: 'user-1',
        editedAt: null,
        commentLiked: false,
        content: 'Agreed, looks amazing!',
        createdAt: '2024-09-30T10:05:00.000Z',
        parentCommentId: 'root-2',
        authorProfile: {
          id: 'user-1',
          firstName: 'Karaflas Eight',
          isStaff: false,
          avatarUri: AVATAR_KARAFLAS,
        },
        totalCommentLikes: 0,
        childCommentCount: 1,
        childComments: [
          {
            id: 'child-2-1-1',
            authorId: 'user-2',
            editedAt: null,
            commentLiked: false,
            content: 'Totally agree with both of you',
            createdAt: '2024-09-30T10:10:00.000Z',
            parentCommentId: 'child-2-1',
            authorProfile: {
              id: 'user-2',
              firstName: 'Go Zero',
              isStaff: false,
              avatarUri: AVATAR_GOZERO,
            },
            totalCommentLikes: 0,
            childCommentCount: 0,
            childComments: [],
          },
        ],
      },
      {
        id: 'child-2-2',
        authorId: 'user-2',
        editedAt: null,
        commentLiked: false,
        content: 'The connecting lines are the best part',
        createdAt: '2024-09-30T10:15:00.000Z',
        parentCommentId: 'root-2',
        authorProfile: {
          id: 'user-2',
          firstName: 'Go Zero',
          isStaff: false,
          avatarUri: AVATAR_GOZERO,
        },
        totalCommentLikes: 2,
        childCommentCount: 0,
        childComments: [],
      },
    ],
  },
  {
    id: 'root-3',
    authorId: 'user-2',
    editedAt: null,
    commentLiked: false,
    content: 'Anyone else notice the line connectors?',
    createdAt: '2024-09-30T09:00:00.000Z',
    parentCommentId: null,
    authorProfile: {
      id: 'user-2',
      firstName: 'Go Zero',
      isStaff: false,
      avatarUri: AVATAR_GOZERO,
    },
    totalCommentLikes: 3,
    childCommentCount: 0,
    childComments: [],
  },
];
